
package com.soap.webclient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderService", targetNamespace = "http://webservice.soap.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.soap.webclient.Order
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.soap.com/OrderService/addOrderRequest", output = "http://webservice.soap.com/OrderService/addOrderResponse")
    public Order addOrder(
        @WebParam(name = "arg0", partName = "arg0")
        Order arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.soap.webclient.Order
     * @throws OrderNotFound_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.soap.com/OrderService/getOrderByIdRequest", output = "http://webservice.soap.com/OrderService/getOrderByIdResponse", fault = {
        @FaultAction(className = OrderNotFound_Exception.class, value = "http://webservice.soap.com/OrderService/getOrderById/Fault/OrderNotFound")
    })
    public Order getOrderById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws OrderNotFound_Exception
    ;

    /**
     * 
     * @return
     *     returns com.soap.webclient.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.soap.com/OrderService/getAllOrdersRequest", output = "http://webservice.soap.com/OrderService/getAllOrdersResponse")
    public ArrayList getAllOrders();

}
