
package com.soap.webclient;

import jakarta.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "OrderNotFound", targetNamespace = "http://webservice.soap.com/")
public class OrderNotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OrderNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public OrderNotFound_Exception(String message, OrderNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public OrderNotFound_Exception(String message, OrderNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.soap.webclient.OrderNotFound
     */
    public OrderNotFound getFaultInfo() {
        return faultInfo;
    }

}
